name: Boannews News Scraper
on:
  schedule:
    - cron: '0 10,20 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  call-template:
    uses: ./.github/workflows/crawler-template.yml
    with:
      crawler-file: boannews_Crawler.py
      output-json: news_json/boannews_News.json
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
