name: FnNews Scraper
on:
  schedule:
    - cron: '12,42 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  call-template:
    uses: ./.github/workflows/crawler-template.yml
    with:
      crawler-file: FnNews_Crawler.py
      output-json: news_json/Fn_News.json
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}      
