name: Google News Scraper
on:
  schedule:
    - cron: '18,48 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  call-template:
    uses: ./.github/workflows/crawler-template.yml
    with:
      crawler-file: Google_Crawler.py
      output-json: news_json/google_News.json
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
