name: SkyDaily News Scraper
on:
  schedule:
    - cron: '6,36 * * * *' # 매일 UTC 08:00 (KST 17:00)에 실행
  workflow_dispatch:     # 수동 실행 가능
permissions:
  contents: write
  
jobs:
  call-template:
    uses: ./.github/workflows/crawler-template.yml
    with:
      crawler-file: SkyDaily_Crawler.py
      output-json: news_json/skyDaily_News.json
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}      
